### ISSUE TITLE
isort behavior inconsistent without explicit src paths

### ISSUE THREAD

**Issue by austinweisgrau** [wyuenho/emacs-python-isort#4]
When using `--profile black`, isort will add a line break to separate different import blocks. Whether or not imports are correctly read as from a local module, and therefore in a separate block, depends on the working directory / src path. This means that if the src path isn't set, isort will behave inconsistently if triggered by this package or run locally.

Ideally this package would determine the src path dynamically for a given buffer and then pass that as a command-line argument to the isort command

If users include a pyproject.toml or .isort.cfg with the appropriate configuration block then this is not necessary

See configuration documentation here: https://pycqa.github.io/isort/docs/configuration/options#src-paths

**Comment by austinweisgrau** [comment]
Could potentially use (projectile-project-root) if the extra dependency is ok

**Comment by wyuenho** [comment]
People define src directories in all sorts of funny ways, this is best left for the users themselves to configure.
